name: WarpsX
version: ${project.version}
main: io.github.reflxction.warps.WarpsX
authors: [Reflxction]
api-version: "1.13"
description: A powerful user-warps plugin
depend:
  - BukkitJSON
softdepend:
  - GriefPrevention
  - Vault